imbhargav5/rooks

- packages/visibility-sensor/index.d.ts
All these keys should be optional.
> Change keys of Options to optional.

- .github/main.workflow
> Remove alias dependency of master-branch-filter

- packages/counter/src/index.js
Not needed but why not as it matches with the rest of the implementation
> Use `incrementBy` instead of `setCounter`

- packages/interval/CHANGELOG.md
- packages/interval/package.json
- packages/interval/src/index.js
I merged Dan Abramov's implementation with the current useInterval hook signature / return value to minimize any breakage. Accordingly, the version bump is only on the last digit (1.2.0 to 1.2.1). I therefore did not need to change the README but I did update the CHANGELOG file. Hope this helps. -Frank
> Updated useInterval using the implementation by Dan Abramov

- packages/keys/.babelrc
- packages/keys/.eslintrc
- packages/keys/.npmignore
- packages/keys/README.md
- packages/keys/index.d.ts
- packages/keys/package.json
- packages/keys/src/index.ts
- packages/keys/src/useKeys.ts
- packages/keys/test/index.spec.js
I am adding the code for further discussions. Let take it from here and discuss what all is needed to be done before it can be merged. I was not able to figure out what all I need to do apart from adding useKeys itself. I think you may help me out with it :)
If you want to see the working useKeys you can checkout here 
https://codesandbox.io/s/p9q7q1l8y7
Done: 
1. useKeys supporting many keys with names to be passed.
2. You can remove the listeners by changing the props option when.
> Adding commit for usekeyshook

- packages/localstorage/src/useLocalstorage.ts
- packages/storybook/src/localstorage.js
- This PR will allow user to store Object, Arrays, Number etc. as well
- Basically this hook is already works as wrapper so we can wrap `JSON.parse()` and `JSON.stringify()` for ease of developers.
> refactor: store object and arrays

- packages/geolocation/.babelrc
- packages/geolocation/.eslintrc
- packages/geolocation/.npmignore
- packages/geolocation/README.md
- packages/geolocation/index.d.ts
- packages/geolocation/package.json
- packages/geolocation/src/index.ts
- packages/geolocation/src/useGeolocation.ts
- packages/geolocation/test/index.spec.js
- packages/rooks/src/index.ts
- packages/shared/tsconfig.tsbuildinfo
- packages/storybook/src/geolocation.js
- packages/storybook/src/index.js
Hi,
This is the implementation of useGeolocation hook. Let's review it and move this forward.
1. Add useGeolocationhook
2. Add test cases.
3. Add storybook example.
> useGeolocationhook

- packages/storybook/src/index.js
- packages/storybook/src/throttle.js
- packages/throttle/.babelrc
- packages/throttle/.eslintrc
- packages/throttle/.npmignore
- packages/throttle/README.md
- packages/throttle/index.d.ts
- packages/throttle/package.json
- packages/throttle/src/index.ts
- packages/throttle/test/index.spec.js
* Add hook to storybook
* Add tests
* Add readme
* Add new hook files
* Add use throttle hook
* Add useEffect and save timer to variable to do a cleanup on unmount.
> Feature/use throttle hook (#94)

- packages/localstorage/src/useLocalstorage.ts
- packages/localstorage/test/index.spec.js
- packages/sessionstorage/src/useSessionstorage.ts
- packages/sessionstorage/test/index.spec.js
Add performance improvement mentioned in https://github.com/imbhargav5/rooks/issues/93
1. usage of useCallback. Done
2. storage event listener is added on each render. Must only be added on mount. Done.
Let me know if I missed anything ?
> adding the perf improvements for useLocalstorage and useSessionstorage

- packages/intersectionobserver/.babelrc
- packages/intersectionobserver/.eslintrc
- packages/intersectionobserver/.npmignore
- packages/intersectionobserver/README.md
- packages/intersectionobserver/index.d.ts
- packages/intersectionobserver/package.json
- packages/intersectionobserver/src/index.ts
- packages/intersectionobserver/src/useIntersectionObserver.ts
- packages/intersectionobserver/test/index.spec.js
- packages/storybook/src/index.js
- packages/storybook/src/intersectionobserver.js
Pending Item:
Codesandbox Intersectionobserver example: https://codesandbox.io/s/useintersectionobserver-nvj3f
1. Test cases
2. More practical example in storybook need to be added
3. discuss the API.
> useIntersectionObserver

- packages/mouse/test/index.spec.js
* test the mouse position is updated when the mouse is moved.
if these tests make sense I could look into adding tests for others. 😄
> test(mouse): add tests for use mouse

- packages/timeout/README.md
> Add documentation for returned isActive property of useTimeout.

- .github/workflows/rebase.yml
Adds a github action that rebases on comment.
> Add rebase github action

- packages/fullscreen/.babelrc
- packages/fullscreen/.eslintrc
- packages/fullscreen/.npmignore
- packages/fullscreen/README.md
- packages/fullscreen/index.d.ts
- packages/fullscreen/package.json
- packages/fullscreen/src/index.ts
- packages/fullscreen/src/useFullscreen.ts
- packages/fullscreen/test/index.spec.js
- packages/storybook/src/fullscreen.js
- packages/storybook/src/index.js
* feat: add useFullscreen
add useFullscreen hook
* fix: update package.json
add missing feilds to package.json
* fix(fullscreen): PR fixes and project standards
* move to forEach
* remove anonymous func in favor of fat arrow
* move logic to its on file
* add index responsible for only exporting (like useMouse)
* fix(fullscreen): default state should be derived from document
* fix default state to derive from document
* fix(fullscreen): return array
return array instead of object
* fix(fullscreen): update readme
update readme example
> Feat/144/add use fullscreen (#150)

- packages/raf/src/useRaf.ts
> Change effect to use use-effect

- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/merge-refs/.babelrc
- packages/merge-refs/.eslintrc
- packages/merge-refs/.npmignore
- packages/merge-refs/Examples.md
- packages/merge-refs/README.md
- packages/merge-refs/package.json
- packages/merge-refs/src/index.ts
- packages/merge-refs/tsconfig.json
- packages/rooks/src/index.ts
- packages/shared/useMergeRefs.ts
- packages/shared/useOutsideClickRef.ts
- yarn.lock
Adds a new hook. 
Merges multiple refs into a single ref.
- useMergeRefs
> Add a use merge refs hook

- packages/key/package.json
- packages/shared/useLocalstorageState.ts
- packages/shared/useSessionstorageState.ts
Value was incorrectly stringified because of listen function.
> Fix listen json parse issue

- packages/docusaurus/docusaurus.config.js
Working docusaurus. Still not great. But good start.
> At least it works

- .prettierrc.json
- package.json
- yarn.lock
As discussed in #345,I have added prettier as a dev-dependency and made a script to format hooks.
Let me know if any other changes are needed 👍
> Enhancement :Add prettier to project

- packages/shared/useNavigatorLanguage.ts
> Add effect to navigator language

- packages/shared/useFullscreen.ts
Fix #404 
Added fallback document.documentElement when element is not present
> Add the documentElement fallback when element is not there

- README.md
As discussed in #472 
I changed readme Installation.
> Readme installation changes 

- docs/useUpdateEffect.md
- versioned_docs/version-5.0.2/useUpdateEffect.md
- versioned_docs/version-v5.0.0/useUpdateEffect.md
Just some fixes for typos in the docs 👍
> Fixed typo in import examples in docs for useUpdateEffect hook

- src/__tests__/useFullscreen.spec.tsx
- src/hooks/useFullscreen.ts
> feat(usefullscreen): pass requestFullscreenOptions

- .npmignore
- package.json
- src/__tests__/useDebounce.spec.tsx
- src/__tests__/useThrottle.spec.tsx
- src/hooks/useDebounce.ts
- yarn.lock
Upgrade ts and other minor changes
> chore(deps): update typescript to 4.3.5

- docs/useThrottle.md
> docs(useThrottle): update useThrottle example and sandbox

- docusaurus.config.js
- package.json
- yarn.lock
> docs: add redirects for old links

- tsconfig.json
> build(tsconfig): include .tsx files in tsconfig

- README.md
- docs/list-of-hooks.md
- docusaurus.config.js
- helpers/docs/index.js
- helpers/update-docusaurus-sidebars/index.js
- sidebars.json
> chore(docs): update sidebar and helpers

- src/__tests__/useMapState.spec.tsx
> chore: Clearer test names

- .all-contributorsrc
- .github/workflows/ci-release.yml
- helpers/update-all-contributors/index.ts
- package.json
- src/pages/_CONTRIBUTORS.md
- src/pages/index.js
- src/pages/styles.module.css
- yarn.lock
> chore(helpers): add all-contributors tools

- docs/useDebouncedValue.md
- helpers/hooks-list.json
- src/__tests__/useDebouncedValue.spec.ts
- src/hooks/useDebouncedValue.ts
- src/index.ts
WIP - just hook + tests, without example, mds etc as I want to make sure I understood correctly what this hook is supposed to be doing :)
> feat(useDebouncedValue): add useDebouncedValue hook

- docs/useMutationObserverRef.md
> docs(userMutationObserverRef): fix examples and code sandboxes

- docs/useDebouncedValue.md
> docs(useDebouncedValue): fix example and add codesandbox

- src/index.ts
> add useRefElement to index

- docs/useBoundingclientrect.md
> Typo in useboundingclientrect hook

- docs/list-of-hooks.md
- docs/useRefElement.md
- helpers/hooks-list.json
> docs(useRefElement): add to hook list and add to docs

- src/hooks/useKeyBindings.ts
As discussed in https://github.com/imbhargav5/rooks/discussions/609
> :label: updated useKeyBindings callback type

- .github/workflows/ci-release.yml
- .github/workflows/pr.yml
- .mergify.yml
This change has been made by @imbhargav5 from https://mergify.com config editor.
> ci(Mergify): configuration update

- src/__tests__/useMutationObserver.spec.tsx
- src/hooks/useMutationObserver.ts
1. Added unit tests for the `useMutationObserver` hook.
2. Removed unused variable.
> feat: add unit tests for useMutationObserver

- docusaurus.config.js
Hi, this is my first open source contribution.
please tell me if something wrong.
> fix: remove netlify badge

- docusaurus.config.js
- src/css/customTheme.css
> docs: fix website header github link style

- src/hooks/useMultiSelectableList.ts
- src/hooks/useSelectableList.ts
> fix(usemultiselectablelist): fix type of matchSelection

- src/hooks/useWillUnmount.ts
> fix(usewillunmount): revert usewillunmount bug commit

- src/__tests__/generalSsrTests.spec.ts
- src/hooks/useOnWindowResize.ts
- src/hooks/useOnWindowScroll.ts
> Revert "fix: Remove console.warn in SSR"

- docs/useRaf.md
Updates the documentation for useRaf to specify what the timeElapsed value is and demonstrate how it might be used.
> docs: Update useRaf to document timeElapsed

- src/__tests__/useMapState.spec.tsx
- src/hooks/useMapState.ts
Added generics.
---
close #585
> feat: generics for useMapState

- .changeset/clever-hounds-exist.md
- .vscode/settings.json
- data/hooks-list.json
- docs/useAsyncEffect.md
- packages/rooks/src/__tests__/useAsyncEffect.spec.ts
- packages/rooks/src/hooks/useAsyncEffect.ts
- packages/rooks/src/index.ts
* Write useAsyncEffect hook and test
* Add a new test for useAsyncEffect
* Docs
* Fix useAsyncEffect cleanup
* Add docs
* Test for error message
> feat: Add useAsyncEffect (#1146)

- CONTRIBUTING.md
> added: changeset information to contribution guide

- .changeset/dirty-clocks-happen.md
- .husky/_/husky.sh
- data/docs/useArrayState.md
- data/docs/useSetState.md
- data/hooks-list.json
- packages/rooks/src/__tests__/useArrayState.spec.ts
- packages/rooks/src/__tests__/useSetState.spec.ts
- packages/rooks/src/hooks/useArrayState.ts
- packages/rooks/src/hooks/useSetState.ts
- packages/rooks/src/index.ts
- packages/rooks/src/types/types.ts
- Adds  useArrayState and a useSetState hooks to manage an array's state and a set's state in Rooks.
> useArraystate and useSetState

- data/docs/useFullscreen.md
> Update useFullscreen docs

- packages/rooks/src/hooks/useDebounce.ts
> Cancel any pending function calls when unmount

- .changeset/config.json
- .github/workflows/ci-release.yml
I'd like to propose to use changeset to generate changelogs and release descriptions. Drop current scripts (yarn version).
The goal is to have more useful desc in the changelogs
-  PR link
- author
- ...
Will give more insights... 
@imbhargav5 do you have any thoughts about this ? I'm quite experienced with what I can do with changesets and open to exchange pro/cons, but don't really know the current system. Is there interest ?
> Changeset improvements (suggestion)

- packages/rooks/src/hooks/useDebounce.ts
- packages/rooks/src/types/utils.ts
I suggest replacing the type of arguments for UnknownFunction.
See https://github.com/imbhargav5/rooks/issues/1411
> Fix: UnknownFunction type mismatch

- .changeset/strange-students-smell.md
- packages/rooks/src/__tests__/useLocalstorageState.spec.tsx
- packages/rooks/src/hooks/useLocalstorageState.ts
Fix https://github.com/imbhargav5/rooks/issues/1566
> fix: `useLocalstorageState` bug fix "undefined"

- apps/website/next.config.ts
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/imbhargav5/rooks/pull/1782?shareId=68892e5c-83c2-4476-a341-7da4c800823c).
> Replace remotePatterns with domains in next.config.ts

- apps/website/next.config.ts
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/imbhargav5/rooks/pull/1783?shareId=458e1fb1-f83b-4a4e-b1da-667fa006c4c4).
> Update next.config.ts to set images unoptimized to true

- ideas.md
Add `ideas.md` proposing new React hooks based on modern Web APIs (2020-2025) and data structures, including usage signatures and explanations of their benefits as hooks.
> Compile hooks for rooms package
