imbhargav5/rooks

packages/visibility-sensor/README.md, packages/visibility-sensor/index.d.ts
* make Options partial (I think it's clearer than having all keys ending with `?`)
* fix types according to documentation
* small formatting issue in readme
=> Fix Options type for visibility-sensor

README.md
=> DOCS: Fix typo mistake on the installation command instruction of the standalone package

packages/localstorage/README.md, packages/localstorage/src/useLocalstorage.ts, packages/sessionstorage/README.md, packages/sessionstorage/src/useSessionstorage.ts, packages/storybook/.storybook/addons.js, packages/storybook/.storybook/webpack.config.js, packages/storybook/src/localstorage.js, packages/storybook/src/sessionstorage.js
- Using array over object for destructring allows user to easily use flexible variable names
- Official react also uses the same approach for hooks like [`useEffect`](https://reactjs.org/docs/hooks-effect.html).
```jsx
// Previously
const {value, set, remove} = useLocalstorage("my-value", 0);
// With array flexible variable naming
const [myValue, setMyValue, removeMyValue] = useLocalstorage("my-value", 0);
```
=> using array instead of object so variables can be renamed easily

packages/geolocation/src/useGeolocation.ts, packages/geolocation/test/index.spec.js
This pr fixes the issue mentioned in issue [https://github.com/imbhargav5/rooks/issues/103](url)
1. Fix the infinite loop issue:
Happening due to the options object being sent as a new reference always and effect running again and again. Now I have spread the options
2. Add test case for the infinite loop issue.
=> Fix infinite loop issue and add test case for it

packages/localstorage/src/index.ts, packages/localstorage/src/useLocalstorage.ts, packages/localstorage/test/index.spec.js, packages/sessionstorage/src/index.ts, packages/sessionstorage/src/useSessionstorage.ts
Resolves #148  
- classname from `useLocalStorage` to `useLocalstorage`
- classname from `useSessionStorage` to `useSessionstorage`
=> Localstorage and Sessionstorage typo fix

packages/navigator-language/src/useNavigatorLanguage.ts
This removes the useState and useEffect hook calls and just returns the value on the navigator as is.
It should stop unwanted reflow caused by the effect updating the state on load.
closes [#212]
=> Return the navigator language property as is

packages/geolocation/src/useGeolocation.ts
The function `getGeoLocation` works as expected and rejects the Promise how it should, but inside the `useEffect` there was no catching this error.
Wrapping with a try catch yields the expected behaviour.
=> fix(useGeolocation): catch unhandled error to return error status and message

packages/storybook/src/index.js, packages/storybook/src/undo-state.js, packages/undo-state/.babelrc, packages/undo-state/.eslintrc, packages/undo-state/.npmignore, packages/undo-state/README.md, packages/undo-state/index.d.ts, packages/undo-state/package.json, packages/undo-state/src/index.d.ts, packages/undo-state/src/index.ts, packages/undo-state/src/useUndoState.ts, packages/undo-state/test/index.spec.js
Drop in replacement for useState hook but with undo functionality.
Only difference is that hook returns third undo function parameter that when called undo's the last step.
Also for memory optimization the hook accepts `options.maxSize` argument that limits how many steps are preserved in history.
```jsx
const Demo = () => {
const [value, setValue, undo] = useUndoState(0)
return (
<div>
<span>Current value: {value}</span>
<button onClick={() => setValue(value + 1)}>
Increment
</button>
<button onClick={undo}>
Undo
</button>
</div>
)
}
render(<Demo/>)
```
You can pass any kind of value to hook just like React's own useState.
```jsx
const Demo = () => {
const [value, setValue, undo] = useUndoState({ data: 42 })
return (
<div>
<span>Current value: {value}</span>
<button onClick={() => …
```
=> useUndoState hook

packages/shared/useVisibilitySensor.ts
Use the existing isomorphic hook to prevent warnings
=> Ensure visibility check doesn't throw warnings on SSR

.github/workflows/version-bump.yml, .prettierignore, helpers/create.js, package.json, yarn.lock
When the user runs `git commit` this will trigger prettier in "write" mode so it will automatically lint the files according to the prettier configuration the repo already has at `.prettierrc`.
Also moved prettier to `devDependencies` but feel free to disagree with me there.
Close #380
=> Add prettier pre-commit hook

packages/shared/useTimeout.ts
Currently, `useTimeout` does not react on `timeoutDelayMs` param change.
Example code:
```tsx
function MyComponent() {
const [interval, setInteval] = useState(0);
const { start, clear } = useTimeout(() => doSomething(), interval);
return (
...
<input onChage={e => setInterval(e.target.value)} />
...
);
}
```
New `interval` value won't be used until current timeout is finished and new one manually started
=> Restart timeout on interval value change

packages/shared/useFullscreen.ts
Change property `isEnabled` to match mdn documentation.
fix #410
=> fix(usefullscreen): change isenabled fullsrceen property

src/__tests__/useOutsideClick.spec.tsx, src/__tests__/useOutsideClickRef.spec.tsx, src/hooks/useOutsideClick.ts, src/hooks/useOutsideClickRef.ts
issue #530 
The main cause is that the callback is called in event bubbling phase which happens after the click event for icon change
=> fix(useOutsideClickRef): fix child update logic and event listener phase

src/__tests__/useMapState.spec.tsx
Changed `doesnot` to `does not`. Idk if this is a `fix` or a `chore` because it doesn't change actual code, just tests.
=> chore(useMapState): Fix typo in tests

docs/rooks.md, sidebars.json
#545
The cause is that we removed 'rooks' page from sidebar, it corresponds to '/docs' route. Clicking on 'Documentation' brings use to '/docs', so i added it back to sidebar to fis it.
If we don't want rooks page at all. We need to change some other page to be '/docs'
=> docs: fix missing sidebar when click on docmentation

docusaurus.config.js
It's is a small improvement of GitHub's name. 
The right way to write the GitHub name is using the "H" character in uppercase.
https://github.com/logos
ps: I hope my contribution can help you. 
Awesome project, congrats! =D
=> chore(docs): fix typo of the GitHub name

docs/useIntervalWhen.md, src/__tests__/useIntervalWhen.spec.tsx, src/hooks/useIntervalWhen.ts
When using useIntervalWhen there is no possibility to say: invoke the callback right before the interval elapses.
If you use useIntervalWhen for polling a service from the backend this is a very common scenario.
=> Add eager possibility for useIntervalWhen

src/hooks/useCountdown.ts
This resolves a deprecation notice in the console whenever I use `useCountdown`.
```
Warning: useInterval is deprecated, it will be removed in rooks v7. Please use useIntervalWhen instead. 
```
=> useIntervalWhen in useCountdown

src/__tests__/useQueueState.spec.ts, src/__tests__/useStackState.spec.ts, src/hooks/useQueueState.ts, src/hooks/useStackState.ts
Changes to `useStackState` hook:
1. Added `clear` and `isEmpty` methods. 
2. Added unit testings for the above methods.
3. Use `list.length` instead of `length` in the closure to solve this eslint warning.
4. Use generics instead of `any` type. Related issue https://github.com/imbhargav5/rooks/issues/586
=> feat: add more methods for useStackState

src/hooks/useIntersectionObserverRef.ts
In the changed `useIntersectionObserverRef` [#889](https://github.com/imbhargav5/rooks/pull/889),
observation could be stopped by passing undefined to callback,
but callback was not optional, so undefined could not be passed in TS.
So I fixed the type definition.
=> Change callback param type definition to optional

src/hooks/useFullscreen.ts
As per #877, the useFullscreen hook has an incorrect typing of a return value.
=> fix: change useFullscreen hook return type (it never returns undefined)

src/hooks/useDidUpdate.ts
> With the release of React 18, StrictMode gets an additional behavior to ensure it's compatible with reusable state. When StrictMode is enabled, **React intentionally double-invokes effects (mount -> unmount -> mount) for newly mounted components**. [Source](https://github.com/reactwg/react-18/discussions/19)
So, it's essential that the `hasMountedRef` is reset when unmounting otherwise it won't behave desirably when wrapped inside StrictMode.
=> Fix useDidUpdate to make it work with Strict Effects

src/__tests__/generalSsrTests.spec.ts, src/hooks/useOnWindowResize.ts, src/hooks/useOnWindowScroll.ts
The warning was unnecessary for several reasons.
First, The only way to detect SSR seemed to be using `window === undefined`, so detecting it and warning it is redundant.
Reference: https://github.com/alex-cory/use-ssr/blob/master/useSSR.ts
Secondly, in other place rooks calling `useGlobalObjectEventListener`, it does not detect `window === undefined`.
Reference:
https://github.com/imbhargav5/rooks/blob/bcd25dff395a82d51d27d4e1faac3bbbfe1dcd08/src/hooks/useDocumentEventListener.ts#L20
https://github.com/imbhargav5/rooks/blob/bcd25dff395a82d51d27d4e1faac3bbbfe1dcd08/src/hooks/useWindowEventListener.ts#L20
Finally, it violates conditional hooks call rule. The eslint shows error `React Hooks must be called in the exact same order in every component render.`
Reference: …
=> fix: Remove console.warn in SSR

helpers/create/index.ts, helpers/docs/index.ts, helpers/update-title-card/index.ts, package.json, yarn.lock
This pr fixes errors in helpers/create (`yarn new`) as described in #1012 
It:
- adds `?? ""` in two places to remove the possibility of a value being undefined
- removes the dependency on replace-string, adding a custom implementation
Questions for maintainers:
is helpers/create/index.ts the right location for a custom replaceString? It is also referenced in another helper (helpers/update-title-card/index.ts), so it might be more appropriate to place it in a separate file.
=> Fix helpers/create

docs/useAsyncEffect.md, helpers/hooks-list.json, src/__tests__/useAsyncEffect.spec.ts, src/hooks/useAsyncEffect.ts
As per #1142, this PR adds the useAsyncEffect hook.
It turns out that cancelling promises with an AbortController is impossible in JS. Instead, this code gives the user the option to cancel their own effect function by providing an AbortSignal to them.
=> feat: Add useAsyncEffect

.vscode/settings.json, apps/website/.eslintignore, apps/website/.eslintrc.js, apps/website/package.json
- fixed some eslint setup problems
- use `*` to specify the local `packages/rooks` in website dependencies
This way, you can just rebuild rooks to test it locally by:
```sh
yarn dev
yarn --cwd packages/rooks build
```
Please tell me if you disagree with any of these changes.
=> chore: twist eslint setup and dependency specification

data/docs/useKeys.md, packages/rooks/src/__tests__/useKeys.spec.tsx, packages/rooks/src/hooks/useKeys.ts
useKeys seems to work fine except when interrupted by `alert`. 
After some investigation, it seems that `alert` will block js execution and there is no way but to overwrite `window.alert`.
Also, I could not find a way to include the alert in the test, so I could not add new test cases.
- https://stackoverflow.com/a/4867114/8776028
- https://stackoverflow.com/a/13593319/8776028
---
close #1018
=> fix: keyup cannot be detected when blocked by alert etc.

apps/website/src/components/MDXRenderer/components.tsx
I am not familiar with mdx and not sure about the difference between `code` and `pre`, but removing `code` seems to fix the issue.
Before:
After:
close #1208
=> fix: remove code components for mdx

.changeset/hot-panthers-wink.md, CONTRIBUTING.md, data/docs/useKeys.md
- added changeset for useKeys, which I forgot to include in https://github.com/imbhargav5/rooks/pull/1210
- updated the docs for useKeys
I can't find a workflow to use the updated rooks in the docs.
When I `yarn build` and `yarn dev` locally, it still seems to use the outdated rooks in the localhosted website.
=> add: useKeys changeset

.vscode/settings.json, apps/website/package.json, packages/eslint-config-custom/.eslintignore, packages/eslint-config-custom/index.js, packages/eslint-config-custom/package.json, packages/eslint-config-custom/tsconfig.json, packages/rooks/.eslintignore, packages/rooks/.eslintrc.js, packages/rooks/package.json, yarn.lock
Twist eslint config.
- Out of my preference, I removed JSON from vscode's eslint checklist.
- Properly configured eslintrc in eslint-config-custom and rooks.
- A dependency ("grey-matter") was missing in apps/website
Now with this PR, checking eslint from both of the followings works the same:
```sh
yarn lint
yarn --cwd packages/rooks lint
yarn eslint . --ext .ts
```
=> chore: eslint config

.changeset/forty-seals-confess.md, packages/rooks/src/hooks/useKeys.ts
It should be possible to use the ref without having to declare it as null
=> Make useKey target option support undefined

.changeset/shaggy-jars-happen.md, packages/rooks/src/hooks/useMediaMatch.ts
This PR fixes a regression causing crashes in old Safari versions
=> fix(useMediaMatch): safari 13.1 addListener fix

.changeset/healthy-berries-compare.md, packages/rooks/src/hooks/useIntersectionObserverRef.ts
Fixed an issue where the `IntersectionObserver` object was recreated and the callback was called excessively whenever the `options` or `callback` argument changed, even if the intersection state did not change.
```ts
const doSomethingWithEntry = useCallback(([entry]) => {
// do something with entry
}, [ ...deps ]);
const callbackRef = useRef(doSomethingWithEntry);
callbackRef.current = doSomethingWithEntry;
const callback = useCallback((...args) => {
return callbackRef.current?.(...args);
}, []);
const ref = useIntersectionObserverRef(
callback,
useMemo({ threshold: 0.5 }, [])
);
```
````ts
const callback = useCallback(([entry]) => {
// do something with entry
}, [ ...deps ]);
const ref = useIntersectionObserverRef(callback, { threshold: 0.5 });
```
=> Reduce the frequency of `useIntersectionObserver` callback execution

packages/rooks/src/hooks/useResizeObserverRef.ts
The same problem with #1568 also existed with `useMutationObserver` and we fixed it.
This issue can also be seen in examples in the [official documentation](https://rooks.vercel.app/docs/useResizeObserverRef).
Since a new callback is created and passed every render, then the callback is called because new `ResizeObserver` is created, and since the callback is changing the state of `resizeCount`, so it re-renders infinitely.
Additionally, it would be nice to be able to cancel observing using a nullish callback like `useIntersectionObserver`, so I modified it the same way.(ref: #897)
=> Prevent excessive call of resize observer callback

packages/rooks/src/__tests__/useDebouncedValue.spec.ts, packages/rooks/src/hooks/useDebouncedValue.ts
=> fix(useDebouncedValue): types of useDebouncedValue will only add null to the union if initializeWithNull was passed

.changeset/stale-poets-walk.md, packages/rooks/src/__tests__/useLocalstorageState.spec.tsx, packages/rooks/src/hooks/useLocalstorageState.ts
In https://github.com/imbhargav5/rooks/commit/adaaad1725977d539f5bda8c1fc8ee8358bd6a49#diff-b0add5bafe9b472c2eb73a766b1fde5062317a10e944f82725c1d782ccc7d6bf the possibility of using a function to generate the next state for `useLocalstorageState` was added. Unfortunately, this was done by adding the current value as a dependency of set, which meant its identity changed every time it is used. This is not the behaviour of `useState` and is not ideal – and most importantly its not necessary. We can just read the value from a ref instead.
This PR does that, and adds extra tests to ensure the identity of set (and remove) doesn't change when used.
=> useLocalstorageState: Ensure the identity of set/remove don't change when used

packages/rooks/src/hooks/useNativeMapState.ts
This will prevent bugs where people try to directly modify the map. By making it a `ReadonlyMap`, they will have TypeScript errors which will remind them to modify mapControls instead of map.
=> Fix: return type `ReadonlyMap` in useNativeMapState

packages/rooks/package.json, pnpm-lock.yaml
Currently the react version is pinned, even though it's not necessary (as far as I've tested). Therefore I unpinned version to support more upstream react versions
=> fix: unpin react version
